### ISSUE TITLE
BuilderBiomeSettings(BuilderBiomeSettings) doesn't copy effects

### ISSUE THREAD

**Issue by Juuxel** [TerraformersMC/Terraform#15]
This causes an exception with templates:

```
java.lang.IllegalStateException: You are missing parameters to build a proper biome for TerraformBiome
BiomeBuilder{
surfaceBuilder=net.minecraft.world.gen.surfacebuilder.ConfiguredSurfaceBuilder@41c983d3,
precipitation=RAIN,
biomeCategory=RIVER,
depth=-0.45,
scale=0.0,
temperature=0.7,
downfall=0.8,
specialEffects=null,
parent='null'
}
	at net.minecraft.world.biome.Biome.<init>(Biome.java:284)
	at com.terraformersmc.terraform.biome.builder.TerraformBiome.<init>(TerraformBiome.java:31)
	at com.terraformersmc.terraform.biome.builder.TerraformBiome.<init>(TerraformBiome.java:25)
	at com.terraformersmc.terraform.biome.builder.TerraformBiome$Builder.build(TerraformBiome.java:124)
	at juuxel.lakeside.biome.LakesideBiomes.<clinit>(LakesideBiomes.kt:77)
	... 14 more
```

**Comment by coderbot16** [comment]
Not sure when this was fixed, but this issue does not exist in the 1.16.2/1.16.3 version of Terraform.
